# Generated by Django 5.1.2 on 2024-10-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='classification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='texts',
            name='text_response',
            field=models.TextField(null=True),
        ),
    ]
